export type { AgentLoopContext, OpportunitySeed, AgentStepResult } from './types.js'
export { TierGate } from './gates/tier-gate.js'
export type { Tier, Channel, Model, OversightMode, GeoOptimizationLevel, ChannelLimit } from './gates/tier-gate.js'
export { OpportunityScorer } from './intelligence/opportunity-scorer.js'
export type { OpportunityScoreInput } from './intelligence/opportunity-scorer.js'
export { Deduplicator } from './intelligence/deduplicator.js'
export type { KeywordItem } from './intelligence/deduplicator.js'
export { CadenceLimiter } from './planning/cadence-limiter.js'
export { OversightGate } from './gates/oversight-gate.js'
export type { OversightDecision, OversightAction, ApprovalStatus } from './gates/oversight-gate.js'
export { LockManager } from './loop/concurrency.js'
export type { AcquireLockResult } from './loop/concurrency.js'
export { AgentLoop } from './loop/agent-loop.js'
export type { RunResult, AgentLoopOptions } from './loop/agent-loop.js'
export { EscalationManager } from './gates/escalation.js'
export type { EscalationReport } from './gates/escalation.js'
