export type { AgentLoopContext, OpportunitySeed, AgentStepResult } from './types'
export { TierGate } from './gates/tier-gate'
export type { Tier, Channel, Model, OversightMode, GeoOptimizationLevel, ChannelLimit } from './gates/tier-gate'
export { OpportunityScorer } from './intelligence/opportunity-scorer'
export type { OpportunityScoreInput } from './intelligence/opportunity-scorer'
export { Deduplicator } from './intelligence/deduplicator'
export type { KeywordItem } from './intelligence/deduplicator'
export { CadenceLimiter } from './planning/cadence-limiter'
export { OversightGate } from './gates/oversight-gate'
export type { OversightDecision, OversightAction, ApprovalStatus } from './gates/oversight-gate'
export { LockManager } from './loop/concurrency'
export type { AcquireLockResult } from './loop/concurrency'
export { AgentLoop } from './loop/agent-loop'
export type { RunResult, AgentLoopOptions } from './loop/agent-loop'
export { EscalationManager } from './gates/escalation'
export type { EscalationReport } from './gates/escalation'
export { AiAnswerAnalyzer } from './intelligence/ai-answer-analyzer'
export type { AiAnswerOpportunity, SnapshotInput } from './intelligence/ai-answer-analyzer'
